---
# sonarqube_version: 6.7
sonarqube_version: 7.9.1

adoptopenjdk:
  version: "jdk11_0411_oj9" # for SonarQube 7.9.1
  # version: "jdk8_222b10_oj9" # for Oracle 12.2

c2_alias:
  roles:
    sonarqube:
      logs: ["{{ sonarqube_home }}/sonarqube/logs/*.log"]
      configs: 
        - "{{ sonarqube_home }}/sonarqube/conf/sonar.properties"
        - "/etc/systemd/system/sonarqube.service" 

https_proxy_roles:
  sonarqube:
    hostname: sonarqube.tech
    proxy_port: 443
    port: "{{ sonarqube_web_port }}"
    context: "{{ sonarqube_web_context }}"

sonarqube_java_bin: 
  Debian: '{{ adoptopenjdk_java_home }}/bin/java'
  RedHat: '{{ adoptopenjdk_java_home }}/bin/java'

sonarqube_proxy:
  host: '{{ proxy_host }}'
  port: '{{ proxy_port }}'  

sonarqube_ldap:
  url: ldap://1.1.1.3:389
  bindDn: cn=admin
  authentication: simple
  #authentication: DIGEST-MD5
  user: 
    baseDn: ou=people,dc=cicd,dc=tech
    request: uid={login}
    realNameAttribute: cn
    emailAttribute: mail
  group: 
    baseDn: ou=groups,dc=cicd,dc=tech
    request: (&(objectClass=groupOfNames)(member={dn}))
    idAttribute: cn

apache_remove_default_vhost: true

sonarqube_jmx_remote:
  enable: yes