---
# nexus_version: 3.19.1-01
nexus_version: 3.20.1-01
nexus_public_hostname: sh.1.1.1.3.nip.io
nexus_public_scheme: https
nexus_upgrade: true

nexus_default_context_path: /nexus

nexus_api_hostname: sh.1.1.1.3.nip.io
nexus_api_scheme: https
nexus_api_validate_certs: false
nexus_api_context_path: /nexus/
nexus_api_port: 443

nexus_ldap_realm: true
ldap_connections: 
  - ldap_name: OpenDJ LDAP
    ldap_protocol: ldap
    ldap_hostname: 1.1.1.3
    ldap_port: 389
    ldap_use_trust_store: false  # Wether or not to use certs in nexus trust store
    ldap_auth: simple
    ldap_auth_username: cn=admin
    ldap_auth_password: "{{ opendj_password }}"
    ldap_search_base: dc=cicd,dc=tech
    ldap_user_base_dn: ou=people
    ldap_user_filter: (uid=*)
    ldap_user_object_class: inetOrgPerson
    ldap_user_id_attribute: uid
    ldap_user_real_name_attribute: cn
    ldap_user_email_attribute: mail
    ldap_map_groups_as_roles: true
    ldap_map_groups_as_roles_type: static
    ldap_group_base_dn: ou=groups
    ldap_group_object_class: groupOfNames
    ldap_group_id_attribute: cn
    ldap_group_member_attribute: member
    ldap_group_member_format: uid=${username},ou=people,dc=cicd,dc=tech
    ldap_group_subtree: true

apache_remove_default_vhost: true

nexus_config_gitlfs: true

nexus_content_selectors:
- name: all-gitlfs
  description: Selector for Git LFS repositories
  search_expression: format=="gitlfs"

#backup_restore: 
#  nexus:
#    path_pattern: '*'
#    folder: data
#    remove_folder: data/groovy-raw-scripts/
#    force: false
#    stop_start_service: nexus
