---
reverse_proxy_vhosts:
  sh:
    server_name: sh.1.1.1.3.nip.io 
    port: 443
    proxy_verify: false
    proxy_passes:
      - name: sonarqube
        proxy_pass: /sonarqube https://1.1.1.4/sonarqube
      - name: nexus
        proxy_pass: /nexus http://1.1.1.7:8081/nexus nocanon
        proxy_pass_reverse: /nexus http://1.1.1.7:8081/nexus
      - name: jenkins
        proxy_pass: /jenkins http://1.1.1.9:8080/jenkins nocanon
        proxy_pass_reverse: /jenkins http://1.1.1.9:8080/jenkins
      - name: bitbucket
        proxy_pass: /bitbucket http://1.1.1.11:7990/bitbucket
      - name: confluence
        proxy_pass: /confluence http://1.1.1.12:8090/confluence
      - name: jira
        proxy_pass: /jira http://1.1.1.13:8080/jira
      - name: dimension-with-key
        proxy_pass: /dimension-with-key http://1.1.1.10:8080/dimension-with-key
      - name: dimension
        proxy_pass: /dimension http://1.1.1.10:8080/dimension
      - name: angularblog
        proxy_pass: /angularblog http://1.1.1.10:8080/angularblog
  awx:
    server_name: awx.1.1.1.3.nip.io 
    port: 443
    proxy_verify: false
    proxy_passes:
      - name: awx
        proxy_pass: / http://1.1.1.5:80/
    custom_directives:
      - RewriteEngine on
      - RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
      - RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
      - RewriteRule .* ws://1.1.1.5:80%{REQUEST_URI} [P]
  jira:
    server_name: jira.1.1.1.3.nip.io 
    port: 443
    proxy_verify: false
    proxy_passes:
      - name: jira
        proxy_pass: /jira http://1.1.1.13:8080/jira

reverse_proxy_global_favicon: favicon-blue.ico
